apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-booking-service
  template:
    metadata:
      labels:
        app: flight-booking-service
      annotations:
        kubectl.kubernetes.io/restartedAt: "{{ .Date.Unix }}"
    spec:
      containers:
        - name: flight-booking-service
          image: pavankd12/flight-booking-service:latest
          envFrom:
            - configMapRef:
                name: flight-booking-service-config
          imagePullPolicy: Always
          ports:
            - containerPort: 50002
          resources:
            requests:
              memory: "128Mi" # Reduced memory request
              cpu: "250m" # Reduced CPU request
            limits:
              memory: "256Mi" # Reduced memory limit
              cpu: "500m" # Reduced CPU limit
