apiVersion: v1
kind: Service
metadata:
  name: flight-booking-service-lb
  labels:
    app: flight-booking-service
spec:
  selector:
    app: flight-booking-service # Matches the app label in your deployment
  ports:
    - protocol: TCP
      port: 50002 # The port exposed externally
      targetPort: 50002 # The port on your container
  type: LoadBalancer # Expose the service externally
