name: Deploy booking-service-golang

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1 # Specify version
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG="${{ github.sha }}"
          docker build --no-cache \
            --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_NAME=${{ secrets.DB_NAME }} \
            --build-arg DB_PORT=${{ secrets.DB_PORT }} \
            --build-arg DB_PW=${{ secrets.DB_PW }} \
            --build-arg DB_UN=${{ secrets.DB_UN }} \
            -t ${{ secrets.DOCKER_USERNAME }}/booking-service-golang:${IMAGE_TAG} \
            -t ${{ secrets.DOCKER_USERNAME }}/booking-service-golang:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/booking-service-golang:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/booking-service-golang:latest

      - name: Update Kubernetes deployment
        run: |
          # Get current timestamp
          TIMESTAMP=$(date +%s)

          # Update the image tag in deployment file
          sed -i "s|kubectl.kubernetes.io/restartedAt:.*|kubectl.kubernetes.io/restartedAt: '$TIMESTAMP'|" k8s/booking-service-golang-deployment.yaml
          sed -i 's|image: ${{ secrets.DOCKER_USERNAME }}/booking-service-golang:.*|image: ${{ secrets.DOCKER_USERNAME }}/booking-service-golang:${{ github.sha }}|' k8s/booking-service-golang-deployment.yaml

          # Apply the changes
          kubectl apply -f k8s/booking-service-golang-config.yaml
          kubectl apply -f k8s/booking-service-golang-deployment.yaml
          kubectl apply -f k8s/booking-service-golang-service.yaml

      # - name: Force rollout restart
      #   run: |
      #     kubectl rollout restart deployment booking-service-golang-deployment
      #     kubectl rollout status deployment booking-service-golang-deployment
